### PR TITLE
adding grab/ungrab methods

### PR DESCRIPTION
**Pull request by jackmanlabs**
This just implements a helper for EVIOCGRAB. I needed it to write a mapper for my Logitech G600 mouse. Thanks!

### CODE REVIEW

**Comment by gvalkov** [comment]
Hi. I just merged #6, which also adds wrappers around `EVIOCGRAB` - I like both your PRs, they both work ... it's just unfortunate that two people decided to implement the same functionality on the same day. Thanks for the PR anyhow.

**Comment by muesli** [comment]
@gvalkov @jackmanlabs Heh, crazy timing! Glad to see this project is still active!

**Comment by jackmanlabs** [comment]
Just in case you're interested, this is how I used it:

https://github.com/jackmanlabs/evdeverator

**Comment by muesli** [comment]
And again... I pretty much did the same thing: https://github.com/muesli/magicwand :laughing:

Are you my long-lost twin brother?

**Comment by gvalkov** [comment]
Happy to hear golang-evdev is useful :+1: .

**Pull request closed without merging**
